# Generated by Django 4.1.5 on 2023-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkdin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsup',
            field=models.URLField(),
        ),
    ]
