# Generated by Django 4.1.5 on 2023-01-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_user_facebook_alter_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
