# Generated by Django 4.1.5 on 2023-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_clients_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
