# Generated by Django 4.1.5 on 2023-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_langueges_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langueges',
            name='grade',
            field=models.CharField(choices=[('1', 'elementry'), ('2', 'midLevel'), ('3', 'professional')], max_length=32, null=True),
        ),
    ]
